### ISSUE TITLE
Will there be new releases?

### ISSUE THREAD

**Issue by Gatoz97** [iwrqk/iwrqk#1]
Hey, iwara has launched its official app but as i thught i still prefer this one.
Will there be further updates?
The video browsing doesn't rotate and stays in portrait mode for example.
Thanks and good work.

**Comment by aihermmit** [comment]
啊？什么官方应用程序，不会是awara吧，那不也是第三方的吗？还是我落后了。抱歉我不懂技术，我只会在GitHub上闲逛找找东西。
