### ISSUE TITLE
安装包不能升级安装，只能卸载重装

### ISSUE THREAD

**Issue by EasyRain** [iwrqk/iwrqk#16]
到目前为止都只能卸载重装，升级安装就不行，我还开了核心破解都不行
![Screenshot_2023-08-13-10-33-14-564_com microsoft emmx](https://github.com/iwrqk/iwrqk/assets/46843500/76f04769-515f-48c0-a2e0-bc01440b0410)
![Screenshot_2023-08-13-10-34-31-845_com sevtinge cemiuiler](https://github.com/iwrqk/iwrqk/assets/46843500/744c5378-92cf-40f7-8859-c627f6824d72)

**Comment by qertyuy** [comment]
是的

**Comment by iwrneko** [comment]
GitHub actions 打包问题导致签名没有应用，已修复。不过只有1.2.2以后版本才应用了签名可以直接更新
