### ISSUE TITLE
iwrqk无法正常注册

### ISSUE THREAD

**Issue by the-shy-0805** [iwrqk/iwrqk#18]
iwrqk无法正常注册，显示连接超时。 
![屏幕截图 2023-09-01 231110](https://github.com/iwrqk/iwrqk/assets/143609484/1e7b6a18-d088-4926-85c9-327a51ddf14f)

**Comment by the-shy-0805** [comment]
用的是MuMu12

**Comment by iwrneko** [comment]
网络问题，与iwrqk无关
