### ISSUE TITLE
下载任务有时会卡在“下载中”状态导致无法删除或继续下载

### ISSUE THREAD

**Issue by cykalet** [iwrqk/iwrqk#20]
![Screenshot_20230914-070924~2](https://github.com/iwrqk/iwrqk/assets/70375821/4d9ff18b-3640-4946-9e5d-75b9fe2c918e)
↑比如这样，按说已经下载完成，但退出软件、断开网络等不会改变其状态，没法触发左滑的删除选项，也因为“下载任务已存在”没法重新下载😓

**Comment by iwrneko** [comment]
我的，少考虑了这个情况。不过其实那个“下载中”的标签是可以交互的（

**Comment by cykalet** [comment]
> 我的，少考虑了这个情况。不过其实那个“下载中”的标签是可以交互的（

“交互”指的是点击暂停吗？我遇到的这个没反应
