### ISSUE TITLE
iPad播放界面灰屏

### ISSUE THREAD

**Issue by jiangshijie0** [iwrqk/iwrqk#24]
iPad安装1.2.5后，视频播放界面灰屏，右划可以退出，可以登陆应该不是网络问题

iPadOS 17.1
芯片M1

![IMG_0138](https://github.com/iwrqk/iwrqk/assets/24545352/bd69440c-f62d-4fbc-a5a9-ba13ad4890a2)

**Comment by stvenshaw** [comment]
换回1.2.4吧，我iPhone14pm也这样
