### ISSUE TITLE
请问安装包在哪里？之前下载了一个非常早期的版本，很多功能用不了，到github上没有发现新版本的包

### ISSUE THREAD

**Issue by gcl-l** [iwrqk/iwrqk#3]

**Comment by FenRengXue** [comment]
你好，可以分享一下安装包吗

**Comment by History-exe** [comment]
自己编译

**Comment by RemKeeper** [comment]
https://131admin.lanzout.com/iA77Y10o6pre
密码:cbgv
只编译了arm v7a

**Comment by FenRengXue** [comment]
> https://131admin.lanzout.com/iA77Y10o6pre
> 密码:cbgv
> 只编译了arm v7a

非常感谢你的分享
