### ISSUE TITLE
能不能允许账号登录

### ISSUE THREAD

**Issue by EasyRain** [iwrqk/iwrqk#8]
我账号没有绑定邮箱，虽然尝试过绑定，但是貌似绑定邮箱的系统有问题绑不上，绑定页面都是乱码，所以只能账号登录没法邮箱登录

**Comment by EasyRain** [comment]
![Screenshot_2023-07-23-10-10-43-007_com microsoft emmx](https://github.com/iwrqk/iwrqk/assets/46843500/5e87666f-4079-41d4-844e-ae12b5c7f7b4)
绑定邮箱就显示这个，完全绑不上

**Comment by iwrneko** [comment]
虽然加了，但是还是建议你去官方Discord反馈一下。毕竟这样盗号风险很大。
